export const SORT_BY = 'sortByEvent'
export const FILTER_BY = 'filterByEvent'
export const CLICKED_LENS = 'clickedLensEvent'
export const LENS_EDITED = 'lensEditedEvent'
export const ASC = 'asc'
export const DESC = 'desc'
export const NOT_AVAILABLE = 'N/A'
